Repository 202306-NEA-DZ-FEW/Pebble-work, pull requests merged in 2023-10, with the labels that each got.

#25 feat(signin): create signin page
  src/pages/signin/index.js
  src/styles/globals.css
Labels: enhancement, Feat

#38 34 create events filter
  src/components/Filter/FilterByType.jsx
  src/components/Footer/Footer.jsx
  src/pages/events/index.js
Labels: enhancement, Feat

#40 feat(filter bytype): add functionality with firebase on the filter
  src/components/Filter/FilterByType.jsx
  src/pages/about/index.js
  src/pages/events/index.js
Labels: enhancement, Feat

#62 55 style homepage
  next-i18next.config.js
  next.config.js
  public/Homepage/Girl.png
  public/Homepage/Image (1).png
  public/Homepage/Image (2).png
  public/Homepage/Image.png
  public/Homepage/ManTop.png
  public/Homepage/Oxfams-COVID-19-Relief-Efforts 2.png
  public/Homepage/Square.png
  public/Homepage/attend.png
  src/components/Events/EventCard.jsx
  src/components/Events/EventCardLeft.jsx
  src/components/Filter/FilterByType.jsx
  src/components/Footer/__test__/Footer.test.js
  src/components/HomeCards.jsx
  src/components/Homecards/GalleryCard.jsx
  src/components/Homecards/HeaderCard.jsx
  src/components/Homecards/ImageSquareCard.jsx
  src/components/Homecards/MainCard.jsx
  src/components/Homecards/SocialCard.jsx
  src/components/Navbar/Navbar.jsx
  src/pages/events/index.js
  src/styles/EventCard.module.css
  src/styles/Events.module.css
  src/styles/Homepage.module.css
  src/styles/Navbar.module.css
Labels: bug, enhancement, Styling

#66 style(squarcard homepage): fix responsiveness with homepage 4 images
  src/components/HomeCards.jsx
  src/components/Homecards/ImageSquareCard.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Pebble.jsx
  src/pages/events/index.js
  src/styles/Homepage.module.css
Labels: enhancement, Styling

#70 59 event creation styling for logged out users
  public/Raindrop.png
  public/images/HelpThePoor.jpeg
  src/components/Events/EventCreation.jsx
  src/pages/events/create/index.js
  src/pages/signin/index.js
  src/styles/EventCreation.module.css
Labels: enhancement, Styling

#72 67 handling err with signinup
  src/components/BtnTwitter&Google/Button.jsx
  src/components/Dropdown.jsx
  src/pages/signin/index.js
  src/pages/signup/index.js
Labels: Feat

#74 feat(signin/up page): add pass and email check with regex
  src/pages/signup/index.js
Labels: Feat

#78 77 create UI elements for google and twitter authentication
  src/components/BtnTwitter&Google/Button.jsx
  src/components/BtnTwitter&Google/ButtonGoogle.jsx
  src/components/BtnTwitter&Google/ButtonTwitter.jsx
  src/components/Dropdown.jsx
  src/pages/signin/index.js
  src/pages/signup/index.js
Labels: bug, structure

#79 60 event user data object enhancement
  src/components/Dropdown.jsx
  src/components/Events/EventCard.jsx
  src/components/Events/EventCardLeft.jsx
  src/pages/events/[eventId]/edit.js
  src/pages/events/[eventId]/index.js
  src/pages/events/index.js
  src/pages/index.js
Labels: enhancement, Feat

#83 style(navbar): change in the navbar for the dropdown
  src/components/Cards/Aboutus/MembersCard.jsx
  src/components/Dropdown.jsx
  src/components/Filter/FilterByType.jsx
  src/components/Navbar/Navbar.jsx
  src/pages/about/index.js
  src/styles/Events.module.css
  src/styles/Navbar.module.css
  src/styles/about.module.css
Labels: enhancement, Feat, Styling

#86 feat(noevent page): create a page for events details when the eventId…
  package-lock.json
  package.json
  public/giphy.gif
  src/components/Events/NoEvent.jsx
  src/pages/events/[eventId]/index.js
  src/styles/NoEvent.module.css
Labels: enhancement, Feat

#89 60 event user data object enhancement
  src/pages/events/[eventId]/edit.js
  src/pages/events/[eventId]/index.js
  src/pages/events/create/index.js
Labels: enhancement

#90 88 gmailtwitter accounts
  src/components/Navbar/Navbar.jsx
  src/pages/signup/index.js
Labels: bug, enhancement

#94 92 singupsignin pages
  src/components/Filter/Calendar.jsx
  src/components/Filter/LocationFilter.jsx
  src/pages/events/index.js
  src/pages/signin/index.js
  src/pages/signup/index.js
Labels: enhancement

#95 91 website texts
  public/images/Guidelines.png
  src/components/HomeCards.jsx
  src/components/Homecards/HeaderCard.jsx
  src/components/Homecards/HeroCard.jsx
  src/components/Homecards/MainCard.jsx
  src/pages/events/create/index.js
  src/pages/guidelines/index.js
Labels: enhancement, Feat

#98 96 events + eventcretion
  src/components/Events/EventCard.jsx
  src/components/Events/EventCardLeft.jsx
  src/pages/events/create/index.js
  src/pages/events/index.js
Labels: enhancement, Feat

#102 Event related pages responsiveness
  src/pages/events/[eventId]/edit.js
  src/pages/events/[eventId]/index.js
  src/pages/events/create/index.js
  src/styles/EventDetails.module.css
  src/styles/globals.css
Labels: Styling

#104 perf(event cretion page): change in the code where you press enter, n…
  src/components/Events/PhoneVerify.jsx
  src/components/OtpVerification.jsx
Labels: enhancement

#97 76 date and location filter
  src/components/Filter/Calendar.jsx
  src/components/Filter/FilterByType.jsx
  src/pages/events/create/index.js
  src/pages/events/index.js
Labels: Feat

#108 feat(event details): replace join button with signin/signup for logge…
  src/pages/events/[eventId]/index.js
Labels: Feat
