Repository 202306-NEA-DZ-FEW/Pebble-work, pull requests merged in 2023-11, with the labels that each got.

#111 feat(signin page): add new functionality reset password
  src/pages/signin/index.js
Labels: Feat

#112 style(about/guidelines): add remaining text
  src/pages/about/index.js
  src/pages/guidelines/index.js
Labels: enhancement

#113 Contact us Form
  package-lock.json
  package.json
  src/components/ContactUs.jsx
  src/components/HomeCards.jsx
  src/pages/_app.js
  src/pages/test/index.js
  src/styles/ContactUs.module.css
Labels: bug, enhancement, Feat

#115 build(the user profile page): add the functionalities to the user pro…
  src/pages/profile/index.js
Labels: Feat

#119 Gmail/email accounts binding
  src/pages/events/create/index.js
  src/pages/signin/index.js
Labels: bug, enhancement

#123 99 implement reset password
  src/pages/signin/index.js
Labels: bug

#127 Limited access pages
  public/images/noAccess.jpg
  src/components/Events/EditEvent.jsx
  src/components/Events/EventCreation.jsx
  src/pages/events/[eventId]/edit.js
  src/pages/events/create/index.js
Labels: enhancement, Styling

#124 100 location functionality rework
  src/components/Filter/FirestoreLocation.jsx
  src/pages/events/create/index.js
  src/pages/events/index.js
Labels: bug

#132 27 signinsignup responsive
  src/pages/signin/index.js
  src/pages/signup/index.js
Labels: Feat

#134 style(homepage): fix responsiveness and styling for most components
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/tr/common.json
  public/locales/zh/common.json
  src/components/ContactUs.jsx
  src/components/DateSelector.jsx
  src/components/Events/DesktopEvents.jsx
  src/components/Filter/Calendar.jsx
  src/components/Filter/FirestoreLocation.jsx
  src/components/HomeCards.jsx
  src/components/Homecards/HeaderCard.jsx
  src/components/Homecards/HeroCard.jsx
  src/components/Homecards/MainCard.jsx
  src/components/Navbar/Navbar.jsx
  src/pages/events/create/index.js
  src/pages/signin/index.js
  src/pages/signup/index.js
  src/styles/Homepage.module.css
Labels: enhancement, Styling

#142 style(signup): fix the overlapping of the signup page on some devices
  src/pages/signup/index.js
Labels: enhancement, Styling

#146 135 language button enhancement
  package-lock.json
  package.json
  public/China.png
  public/China.svg
  public/Germany.png
  public/Germany.svg
  public/Turkey.png
  public/Turkey.svg
  public/United-Kingdom.png
  public/United-Kingdom.svg
  src/components/Language/Language.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Translate.jsx
Labels: enhancement, Feat, Styling

#153 feat(the profile,edit profile,pictures library): add styling and resp…
  src/components/Navbar/__test__/Navbar.test.js
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/pages/editprofile/index.js
  src/pages/editprofile/library.js
  src/pages/profile/index.js
Labels: Styling

#151 149 add unit tests for component
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/tr/common.json
  public/locales/zh/common.json
  src/components/BtnTwitter&Google/ButtonGoogle.jsx
  src/components/BtnTwitter&Google/ButtonTwitter.jsx
  src/components/BtnTwitter&Google/__test__/ButtonGoogle.test.js
  src/components/BtnTwitter&Google/__test__/ButtonTwitter.test.js
  src/components/BtnTwitter&Google/__test__/__snapshots__/ButtonGoogle.test.js.snap
  src/components/BtnTwitter&Google/__test__/__snapshots__/ButtonTwitter.test.js.snap
  src/components/Loader/__test__/Loader.test.js
  src/components/Loader/__test__/__snapshots__/Loader.test.js.snap
  src/components/Popup/__test__/Modal.test.js
  src/components/Popup/__test__/__snapshots__/Modal.test.js.snap
Labels: Feat

#148 147 navbar additional enhancement
  package-lock.json
  package.json
  public/icons/Facebook.png
  public/icons/Facebook.svg
  src/components/Footer/Footer.jsx
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Navbar/Navbar.jsx
  src/pages/test/index.js
Labels: enhancement, Feat, Styling

#158 155 members redo
  package-lock.json
  package.json
  src/components/Cards/Aboutus/Members.jsx
  src/components/Cards/Aboutus/TechStack.jsx
  src/components/Cards/Aboutus/Test.jsx
  src/components/Language/Language.jsx
  src/pages/about/index.js
  src/pages/test/TechStack.module.css
  src/pages/test/index.js
  src/styles/TechStack.module.css
  src/styles/globals.css
Labels: enhancement, Feat, Styling

#163 137 translation issue on dynamic pages
  next-i18next.config.js
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/tr/common.json
  public/locales/zh/common.json
  src/components/Events/WideScreenCard.jsx
  src/pages/404.js
  src/pages/events/[eventId]/edit.js
  src/pages/events/[eventId]/index.js
Labels: bug, enhancement

#162 location filter rework
  src/components/Events/SmallScreenEvents.jsx
  src/components/Filter/FirestoreLocation.jsx
  src/pages/signup/index.js
Labels: enhancement

#167 139 add my events section to user profile
  public/locales/de/profile.json
  public/locales/en/profile.json
  public/locales/tr/profile.json
  public/locales/zh/profile.json
  src/pages/profile/index.js
Labels: enhancement

#164 160 events components tests
  jest.setup.js
  package-lock.json
  package.json
  public/horizontal-smoke.png
  public/icons/next.png
  public/icons/next.svg
  public/icons/previous.png
  public/smoke.gif
  src/components/Events/DesktopEvents.jsx
  src/components/Events/EventCreation.jsx
  src/components/Events/MobileEvents.jsx
  src/components/Events/NoEvent.jsx
  src/components/Events/SmallCard.jsx
  src/components/Events/SmallScreenEvents.jsx
  src/components/Events/WideScreenCard.jsx
  src/components/Events/__test__/DesktopEvents.test.js
  src/components/Events/__test__/EditEvent.test.js
  src/components/Events/__test__/EventCardLeft.test.js
  src/components/Events/__test__/EventCreation.test.js
  src/components/Events/__test__/MobileEvents.test.js
  src/components/Events/__test__/NoEvent.test.js
  src/components/Events/__test__/PhoneVerify.test.js
  src/components/Events/__test__/SmallCard.js
  src/components/Events/__test__/SmallScreenEvents.test.js
  src/components/Events/__test__/WideScreenCard.test.js
  src/components/Events/__test__/__snapshots__/DesktopEvents.test.js.snap
  src/components/Events/__test__/__snapshots__/EditEvent.test.js.snap
  src/components/Events/__test__/__snapshots__/EventCardLeft.test.js.snap
  src/components/Events/__test__/__snapshots__/EventCreation.test.js.snap
  src/components/Events/__test__/__snapshots__/MobileEvents.test.js.snap
  src/components/Events/__test__/__snapshots__/NoEvent.test.js.snap
  src/components/Events/__test__/__snapshots__/PhoneVerify.test.js.snap
  src/components/Events/__test__/__snapshots__/SmallScreenEvents.test.js.snap
  src/components/Events/__test__/__snapshots__/WideScreenCard.test.js.snap
  src/components/Filter/Calendar.jsx
  src/components/Language/Language.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Pagination/Pagination.jsx
  src/pages/api/events.js
  src/pages/events/index.js
Labels: bug, enhancement, Feat, test

#166 User images fix (+ tests)
  next.config.js
  src/components/Filter/__test__/Calendar.test.js
  src/components/Filter/__test__/FilterByType.test.js
  src/components/Filter/__test__/FirestoreLocation.test.js
  src/components/Filter/__test__/__snapshots__/Calendar.test.js.snap
  src/components/Filter/__test__/__snapshots__/FilterByType.test.js.snap
  src/components/Filter/__test__/__snapshots__/FirestoreLocation.test.js.snap
  src/pages/editprofile/index.js
  src/pages/profile/index.js
  src/pages/signup/index.js
Labels: enhancement, Feat

#169 165 single click date selection enhancement for calendar
  src/components/Filter/Calendar.jsx
Labels: enhancement

#174 154 user images
  public/images/icon_default.png
  src/components/Dropdown.jsx
  src/pages/editprofile/index.js
  src/pages/profile/index.js
Labels: bug

#177 175 phone verification not working
  public/locales/de/verify.json
  public/locales/en/verify.json
  public/locales/tr/verify.json
  public/locales/zh/verify.json
  src/components/Events/PhoneVerify.jsx
  src/pages/profile/index.js
Labels: bug, enhancement

#183 enhance profile page
  public/images/404.png
  src/pages/404.js
  src/pages/profile/index.js
  src/styles/globals.css
Labels: enhancement, Styling

#187 feat(homecards): add snapshot test to home cards components
  src/components/Homecards/__test__/GalleryCard.test.js
  src/components/Homecards/__test__/HeaderCard.test.js
  src/components/Homecards/__test__/HeroCard.test.js
  src/components/Homecards/__test__/ImageSquareCard.test.js
  src/components/Homecards/__test__/MainCard.test.js
  src/components/Homecards/__test__/SocialCard.test.js
  src/components/Homecards/__test__/__snapshots__/GalleryCard.test.js.snap
  src/components/Homecards/__test__/__snapshots__/HeaderCard.test.js.snap
  src/components/Homecards/__test__/__snapshots__/HeroCard.test.js.snap
  src/components/Homecards/__test__/__snapshots__/ImageSquareCard.test.js.snap
  src/components/Homecards/__test__/__snapshots__/MainCard.test.js.snap
  src/components/Homecards/__test__/__snapshots__/SocialCard.test.js.snap
Labels: test

#188 refactor(add the clickoutside function to the navbar and change the e…
  src/components/Navbar/Navbar.jsx
  src/pages/profile/edit/index.js
  src/pages/profile/edit/library.js
  src/pages/profile/index.js
Labels: enhancement

#190 fix(the profile pictures library): fix the profile pictures library f…
  src/pages/profile/edit/index.js
Labels: bug

#193 186 my event page for users
  public/images/Volunteering-amico.png
  public/images/Volunteering-pana.png
  public/images/Volunteering-rafiki.png
  src/components/Events/DesktopCard.jsx
  src/components/Filter/FirestoreLocation.jsx
  src/pages/dashboard/index.js
Labels: enhancement

#192 184 background animation
  src/components/ContactUs.jsx
  src/components/Dropdown.jsx
  src/components/Events/DesktopCard.jsx
  src/components/Events/DesktopEvents.jsx
  src/components/Events/EventCreation.jsx
  src/components/Events/MobileCard.jsx
  src/components/Events/MobileEvents.jsx
  src/components/Events/NoEvent.jsx
  src/components/Events/PhoneVerify.jsx
  src/components/Events/SmallCard.jsx
  src/components/Events/SmallScreenEvents.jsx
  src/components/Events/__test__/MobileEvents.test.js
  src/components/Events/__test__/SmallScreenEvents.test.js
  src/components/Events/__test__/__snapshots__/MobileEvents.test.js.snap
  src/components/Events/__test__/__snapshots__/SmallScreenEvents.test.js.snap
  src/components/Filter/Calendar.jsx
  src/components/Filter/Dropdown.jsx
  src/components/Filter/FilterByType.jsx
  src/components/Filter/FirestoreLocation.jsx
  src/components/Footer/Footer.jsx
  src/components/HomeCards.jsx
  src/components/Homecards/GalleryCard.jsx
  src/components/Homecards/HeaderCard.jsx
  src/components/Homecards/HeroCard.jsx
  src/components/Homecards/ImageSquareCard.jsx
  src/components/Homecards/MainCard.jsx
  src/components/Language/Language.jsx
  src/components/Loader/Loader.jsx
  src/components/Loader/__test__/__snapshots__/Loader.test.js.snap
  src/components/MorphingSvg.jsx
  src/components/Navbar/Navbar.jsx
  src/components/OtpVerification.jsx
  src/components/Pebble.jsx
  src/components/Signin/Signin.jsx
  src/components/Signup/Signup.jsx
  src/layout/Layout.jsx
  src/pages/404.js
  src/pages/_app.js
  src/pages/about/index.js
  src/pages/api/events.js
  src/pages/events/[eventId]/edit.js
  src/pages/events/[eventId]/index.js
  src/pages/events/create/index.js
  src/pages/events/index.js
  src/pages/guidelines/index.js
  src/pages/index.js
  src/pages/profile/edit/index.js
  src/pages/profile/edit/library.js
  src/pages/profile/index.js
  src/pages/signin/index.js
  src/pages/signup/index.js
  src/pages/test/index.js
  src/styles/EventCard.module.css
  src/styles/Loader.module.css
  src/styles/globals.css
Labels: bug, enhancement, Feat, Styling

#197 191 edit profile page responsiveness
  src/pages/profile/edit/index.js
Labels: Styling, structure

#201 Update README.md
  README.md
Labels: documentation

#196 feat(the profile picture): profile Image type & size check
  src/pages/events/[eventId]/edit.js
  src/pages/events/create/index.js
  src/pages/profile/edit/index.js
Labels: enhancement

#203 194 dashboard responsiveness
  src/components/DropMenu.jsx
  src/components/Events/SmallScreenEvents.jsx
  src/components/Filter/FirestoreLocation.jsx
  src/components/Navbar/Navbar.jsx
  src/pages/404.js
  src/pages/_app.js
  src/pages/dashboard/index.js
  src/pages/events/[eventId]/edit.js
  src/pages/events/[eventId]/index.js
  src/pages/profile/edit/index.js
  src/styles/Events.module.css
  src/styles/Loader.module.css
Labels: bug, enhancement, Feat, Styling

#204 refactor(global): change the text font family globally
  public/logo/Logo.png
  public/nasir-udin-restoraextralight.otf
  src/components/Footer/Footer.jsx
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/pages/_app.js
  src/styles/globals.css
Labels: enhancement, Feat, Styling

#206 Overall text and details fix ups
  public/images/Aazar_BYC.png
  public/images/NotQuby.png
  public/images/hybrid-event-icon.png
  public/locales/de/common.json
  public/locales/en/common.json
  public/locales/tr/common.json
  public/locales/zh/common.json
  src/components/HomeCards.jsx
  src/components/Homecards/GalleryCard.jsx
  src/components/Homecards/HeaderCard.jsx
  src/components/Homecards/HeroCard.jsx
  src/components/Homecards/ImageSquareCard.jsx
  src/components/Homecards/MainCard.jsx
  src/components/Homecards/SocialCard.jsx
  src/components/Homecards/__test__/__snapshots__/GalleryCard.test.js.snap
  src/components/Homecards/__test__/__snapshots__/HeaderCard.test.js.snap
  src/components/Homecards/__test__/__snapshots__/HeroCard.test.js.snap
  src/components/Homecards/__test__/__snapshots__/ImageSquareCard.test.js.snap
  src/components/Homecards/__test__/__snapshots__/MainCard.test.js.snap
  src/components/Homecards/__test__/__snapshots__/SocialCard.test.js.snap
  src/pages/about/index.js
  src/pages/dashboard/index.js
  src/pages/events/[eventId]/index.js
  src/styles/globals.css
Labels: enhancement, Styling

#210 fix(description): add a requirment for creating or editing an event description
  src/components/Language/Language.jsx
  src/pages/events/[eventId]/edit.js
  src/pages/events/create/index.js
Labels: bug

#207 205 meta tags and enhancements
  jest.setup.js
  package-lock.json
  package.json
  public/Volunteer.jpg
  src/components/BtnTwitter&Google/ButtonGoogle.jsx
  src/components/BtnTwitter&Google/ButtonTwitter.jsx
  src/components/Cards/Aboutus/__test__/Members.test.js
  src/components/Cards/Aboutus/__test__/TechStack.test.js
  src/components/Chat/Bubble.jsx
  src/components/Chat/Chat.jsx
  src/components/Chat/ChatDisplay.jsx
  src/components/Chat/__test__/Bubble.test.js
  src/components/Chat/__test__/Chat.test.js
  src/components/Chat/__test__/ChatDisplay.test.js
  src/components/Chat/__test__/__snapshots__/Bubble.test.js.snap
  src/components/Chat/__test__/__snapshots__/Chat.test.js.snap
  src/components/Chat/__test__/__snapshots__/ChatDisplay.test.js.snap
  src/components/DropMenu.jsx
  src/components/Events/__test__/DesktopCard.test.js
  src/components/Events/__test__/DesktopEvents.test.js
  src/components/Events/__test__/EditEvent.test.js
  src/components/Events/__test__/EventCreation.test.js
  src/components/Events/__test__/MobileCard.js
  src/components/Events/__test__/MobileEvents.test.js
  src/components/Events/__test__/NoEvent.test.js
  src/components/Events/__test__/PhoneVerify.test.js
  src/components/Events/__test__/SmallCard.test.js
  src/components/Events/__test__/SmallScreenEvents.test.js
  src/components/Filter/__test__/Calendar.test.js
  src/components/Filter/__test__/FilterByType.test.js
  src/components/Filter/__test__/FirestoreLocation.test.js
  src/components/Footer/__test__/Footer.test.js
  src/components/Homecards/__test__/GalleryCard.test.js
  src/components/Homecards/__test__/HeaderCard.test.js
  src/components/Homecards/__test__/HeroCard.test.js
  src/components/Homecards/__test__/ImageSquareCard.test.js
  src/components/Homecards/__test__/MainCard.test.js
  src/components/Homecards/__test__/SocialCard.test.js
  src/components/Language/Language.jsx
  src/components/Language/__test__/Language.test.js
  src/components/Language/__test__/__snapshots__/Language.test.js.snap
  src/components/Loader/__test__/Loader.test.js
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/Navbar.test.js
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Pagination/Pagination.jsx
  src/components/Pagination/__test__/Pagination.test.js
  src/components/Pagination/__test__/__snapshots__/Pagination.test.js.snap
  src/components/Popup/__test__/Modal.test.js
  src/components/__test__/ContactUs.test.js
  src/components/__test__/DropMenu.test.js
  src/components/__test__/OtpVerification.test.js
  src/components/__test__/__snapshots__/ContactUs.test.js.snap
  src/components/__test__/__snapshots__/DropMenu.test.js.snap
  src/components/__test__/__snapshots__/OtpVerification.test.js.snap
  src/pages/_app.js
  src/pages/test/index.js
  src/styles/Bubble.module.css
  src/styles/Events.module.css
  src/styles/globals.css
Labels: enhancement, Feat, Styling

#212 211 signin button
  README.md
  next-sitemap.config.js
  package-lock.json
  package.json
  public/downscale_images.sh
  public/downscaled/300x300px_scale.jpg
  public/downscaled/AboutPebble_scale.png
  public/downscaled/Girl_scale.png
  public/downscaled/HelpThePoor_scale.jpeg
  public/downscaled/IMG1.png
  public/downscaled/IMG10.png
  public/downscaled/IMG11.png
  public/downscaled/IMG12.png
  public/downscaled/IMG13.png
  public/downscaled/IMG14.png
  public/downscaled/IMG15.png
  public/downscaled/IMG16.png
  public/downscaled/IMG17.png
  public/downscaled/IMG2.png
  public/downscaled/IMG3.png
  public/downscaled/IMG4.png
  public/downscaled/IMG5.png
  public/downscaled/IMG6.png
  public/downscaled/IMG7.png
  public/downscaled/IMG8.png
  public/downscaled/IMG9.png
  public/downscaled/Image (1)_scale.jpg
  public/downscaled/Image (2)_scale.png
  public/downscaled/Image_scale.png
  public/downscaled/ManTop_scale.png
  public/downscaled/Oxfams-COVID-19-Relief-Efforts 2_scale.png
  public/downscaled/Palestine_scale.png
  public/downscaled/Raindrop_scale.png
  public/downscaled/Sitting_scale.png
  public/downscaled/Square_scale.png
  public/downscaled/attend_scale.png
  public/downscaled/event_image_scale.png
  public/favicon.ico
  public/google1a749697a1b533bd.html
  public/next.svg
  src/components/Events/PhoneVerify.jsx
  src/pages/signin/index.js
Labels: bug, enhancement, Feat

#208 202 add restriction to password
  src/pages/profile/edit/index.js
Labels: bug, enhancement, Feat

#214 feat(events page filter buttons): add styling to the events page filt…
  src/components/Events/SmallScreenEvents.jsx
  src/components/Filter/FilterByType.jsx
  src/components/Filter/FirestoreLocation.jsx
Labels: enhancement

#215 Update README.md
  README.md
Labels: documentation

#217 perf(updates): update the dependencies ,slightly change the paginatio…
  next-sitemap.config.js
  package-lock.json
  package.json
  public/locales/de/profile.json
  src/components/Cards/Aboutus/Members.jsx
  src/components/Chat/Chat.jsx
  src/components/Chat/ChatDisplay.jsx
  src/components/ContactUs.jsx
  src/components/DropMenu.jsx
  src/components/Events/DesktopCard.jsx
  src/components/Events/DesktopEvents.jsx
  src/components/Events/EventCreation.jsx
  src/components/Events/MobileEvents.jsx
  src/components/Events/PhoneVerify.jsx
  src/components/Events/SmallCard.jsx
  src/components/Events/SmallScreenEvents.jsx
  src/components/Filter/Calendar.jsx
  src/components/Filter/FirestoreLocation.jsx
  src/components/Filter/__test__/FilterByType.test.js
  src/components/Footer/Footer.jsx
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Homecards/SocialCard.jsx
  src/components/Homecards/__test__/__snapshots__/SocialCard.test.js.snap
  src/components/Navbar/Navbar.jsx
  src/components/Pagination/Pagination.jsx
  src/pages/about/index.js
  src/pages/api/events.js
  src/pages/dashboard/index.js
  src/pages/events/[eventId]/edit.js
  src/pages/events/[eventId]/index.js
  src/pages/events/create/index.js
  src/pages/profile/edit/index.js
  src/pages/profile/index.js
  src/pages/signin/index.js
  src/pages/signup/index.js
  src/styles/Bubble.module.css
  src/styles/DropMenu.module.css
  src/styles/EventCard.module.css
  src/styles/Member.module.css
  src/styles/TechStack.module.css
  src/styles/globals.css
  src/util/firebase.js
Labels: enhancement

#219 218 enhancement
  package-lock.json
  src/components/BtnTwitter&Google/ButtonGoogle.jsx
  src/components/BtnTwitter&Google/ButtonTwitter.jsx
  src/components/BtnTwitter&Google/__test__/__snapshots__/ButtonGoogle.test.js.snap
  src/components/BtnTwitter&Google/__test__/__snapshots__/ButtonTwitter.test.js.snap
  src/components/Chat/Bubble.jsx
  src/components/Chat/__test__/__snapshots__/Bubble.test.js.snap
  src/components/OtpVerification.jsx
  src/components/__test__/__snapshots__/OtpVerification.test.js.snap
  src/pages/events/[eventId]/edit.js
  src/pages/events/create/index.js
  src/pages/profile/edit/index.js
  src/pages/signin/index.js
  src/pages/signup/index.js
Labels: bug, enhancement
